language: python
dist: trusty
sudo: false
python:
  - "2.7"
env:
  DATABASE_URL=mysql://travis@127.0.0.1/mozillians
  BASKET_URL=http://127.0.0.1
  BASKET_API_KEY=basket_api_key
  COMPRESS_ENABLED=False
  COMPRESS_OFFLINE=False
  SECRET_KEY='supersecretkey'
  ALLOWED_HOSTS=localhost
  DEBUG=True
  CELERY_TASK_ALWAYS_EAGER=True
services:
  - elasticsearch
  - mysql
before_install:
  - pip install flake8
  - flake8 mozillians
  - mysql -e 'create database mozillians character set utf8; SET @@GLOBAL.wait_timeout=28800;'
cache:
  - pip
install:
  - npm install -g less
  - pip install coverage
  - pip install --require-hashes --no-deps -r requirements/dev.txt
script:
  - coverage run --source=mozillians manage.py test --noinput
after_success:
  - pip install coveralls
  - coveralls
