---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-celery
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-celery
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-celery
    spec:
      containers:
        - name: {{ .Values.name }}-celery
          image: {{ .Values.docker_registry | default "mozillaparsys" }}/{{ .Values.name }}:{{ .Values.rev }}
          {{ if eq .Values.env "dev" -}}
          imagePullPolicy: IfNotPresent
          {{- else -}}
          imagePullPolicy: Always
          {{- end }}
          {{ if eq .Values.env "staging" -}}
          command: ["/bin/sh"]
          args: ["-c", "cp /etc/secrets-volume/env /code/mozillians/.env && /bin/sh /code/bin/run-celery.sh"]
          {{- else -}}
          command: ['./bin/run-celery.sh']
          {{- end }}
          {{ if eq .Values.env "dev" -}}
          env:
            - name: C_FORCE_ROOT
              value: 'true'
          envFrom:
            - configMapRef:
                name: {{ .Values.config_map }}
          {{- end }}
          {{ if eq .Values.env "staging" -}}
          volumeMounts:
            - mountPath: /etc/secrets-volume/
              name: secrets-volume
          {{- end }}
      {{ if eq .Values.env "staging" -}}
      volumes:
        - name: secrets-volume
          secret:
            secretName: mozillians-dev
      {{- end }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-celery-beat
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-celery-beat
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-celery-beat
    spec:
      containers:
        - name: {{ .Values.name }}-celery-beat
          image: {{ .Values.docker_registry | default "mozillaparsys" }}/{{ .Values.name }}:{{ .Values.rev }}
          {{ if eq .Values.env "dev" -}}
          imagePullPolicy: IfNotPresent
          {{- else -}}
          imagePullPolicy: Always
          {{- end }}
          {{ if eq .Values.env "staging" -}}
          command: ["/bin/sh"]
          args: ["-c", "cp /etc/secrets-volume/env /code/mozillians/.env && /bin/sh /code/bin/run-celery-beat.sh"]
          {{- else -}}
          command: ['./bin/run-celery-beat.sh']
          {{- end }}
          {{ if eq .Values.env "dev" -}}
          env:
            - name: C_FORCE_ROOT
              value: 'true'
          envFrom:
            - configMapRef:
                name: {{ .Values.config_map }}
          {{- end }}
          {{ if eq .Values.env "staging" -}}
          volumeMounts:
            - mountPath: /etc/secrets-volume/
              name: secrets-volume
          {{- end }}
      {{ if eq .Values.env "staging" -}}
      volumes:
        - name: secrets-volume
          secret:
            secretName: mozillians-dev
      {{- end }}

