---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.docker_registry | default "mozillaparsys" }}/{{ .Values.name }}:{{ .Values.rev }}
          {{ if eq .Values.env "dev" -}}
          imagePullPolicy: IfNotPresent
          {{- else -}}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - containerPort: 8000
          command: ['/bin/sh']
          {{ if eq .Values.env "staging" -}}
          args: ["-c", "cp /etc/secrets-volume/env /code/mozillians/.env && /code/bin/run-dev-preview.sh"]
          {{- else -}}
          args: ["-c", "/code/bin/run-dev-preview.sh"]
          {{- end }}
          {{ if eq .Values.env "dev" -}}
          tty: true
          stdin: true
          envFrom:
            - configMapRef:
                name: {{ .Values.config_map }}
          env:
            - name: DUMMY_TIMESTAMP
              value: "{{ now.Unix }}"
          {{- end }}
          {{ if eq .Values.env "staging" -}}
          volumeMounts:
            - mountPath: /etc/secrets-volume/
              name: secrets-volume
          {{- end }}
      {{ if eq .Values.env "staging" -}}
      volumes:
        - name: secrets-volume
          secret:
            secretName: mozillians-dev
      {{- end }}
