---
{{ if eq .Values.env "staging" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: oidc-proxy
  name: oidc-proxy
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: oidc-proxy
    spec:
      containers:
        - image: mozillaparsys/mozilla.oidc.proxy:latest
          imagePullPolicy: Always
          name: oidc-porxy
          ports:
            - containerPort: 80
          env:
            - name: client_id
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: client_id
            - name: client_secret
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: client_secret
            - name: discovery_url
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: discovery_url
            - name: discovery_url
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: discovery_url
            - name: backend
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: backend
            - name: redirect_uri
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: redirect_uri
            - name: allowed_group
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: allowed_group

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-router
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    worker_rlimit_nofile 8192;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      proxy_redirect          off;
      proxy_set_header        Host            $host;
      proxy_set_header        X-Real-IP       $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      client_max_body_size    10m;
      client_body_buffer_size 128k;
      proxy_connect_timeout   90;
      proxy_send_timeout      90;
      proxy_read_timeout      90;
      proxy_buffers           32 4k;

      server {
        listen 80;
        location /beta/avatar/ {
          proxy_pass http://dino-park-avatar:80;
        }
        location ~ ^/beta/(css|img|js)/ {
          proxy_pass http://dino-park-front-end-service:80;
        }
        location / {
          proxy_pass http://dino-park-mozillians-service:80;
        }
      }
    }

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: internal-router
  namespace: {{ .Values.namespace }}
  labels:
    app: internal-router
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: internal-router
    spec:
      volumes:
      - name: nginx-router
        configMap:
          name: nginx-router
      containers:
      - name: nginx-router
        image: nginx
        ports:
        - name: http
          containerPort: 80
        env:
        - name: force_update
          value: "2"
        volumeMounts:
        - name: nginx-router
          mountPath: /etc/nginx/
          readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: internal-router
  name: internal-router
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: internal-router

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: oidc-proxy
  name: oidc-proxy
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    name: oidc-proxy
{{ end }}
